tap "homebrew/command-not-found"
tap "beeftornado/rmtree"

brew "coreutils"
brew "imagemagick"
brew "mas"
brew "zsh"
brew "tmux"

brew "asdf"
brew "git"
brew "neovim"
brew "sbt"

cask "google-chrome"

cask "alacritty"
cask "docker"
cask "postman"

cask "intellij-idea"
cask "visual-studio-code"

cask "obsidian"

cask "telegram"

cask "spotify"

cask "mullvadvpn"
cask "the-unarchiver"
cask "transmission"

mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
mas "Pages", id: 409201541
